### ISSUE TITLE
Dutch language

### ISSUE THREAD

**Issue by BenGoudsmit** [lcreteig/amsterdown#10]
Hi,

I'm using pdfTex as compiler and I have difficulties setting the Dutch language for the summary in Dutch.
Your soluting does not work for me, as I cannot set the Dutch language and its hypens.

Could you please indicate where I should make changes to allow 1 chapter in Dutch?

Thanks!

**Comment by lcreteig** [comment]
Hi,

Without more info it's hard to say what's going wrong exactly... But IIRC, this relies on the following LaTeX packages: `babel-dutch` and `hyphen-dutch`.

Are you using [TinyTeX](https://yihui.org/tinytex/) as your LaTeX distribution? In that case, these packages should be installed automatically. But just in case, could you try running the following commands in R, and then try to render the template again?

```r
tinytex::tlmgr_install("hyphen-dutch")
tinytex::tlmgr_install("babel-dutch")
```

If you're using another LaTeX distribution, you'll instead need to run the following commands in a terminal:

```bash
tlmgr install hyphen-dutch
tlmgr install babel-dutch
```
